package alex;

public enum ClaseLexica {
 IDEN, ENT, REAL, BOOL, TRUE, FALSE, AND, OR, NOT, STRING, NULL, PROCEDIMIENTO, IF, THEN, ELSE, ENDIF,
 WHILE, DO, ENDWHILE,CALL, RECORD, ARRAY, OF, POINTER, NEW, DELETE, READ, WRITE, Nl, VAR, TYPE, LIT_CADENA,
 NUM_ENTERO,NUM_REAL, PAR_APER, PAR_CIER, CORCHE_APER, CORCHE_CIER, CORCHE_RECT_APER, CORCHE_RECT_CIER, IGUAL, 
 IGUAL_IGUAL, MENOR, MAYOR, MENOR_IGUAL, MAYOR_IGUAL, DISTINTO, SEP_SECCION, AMPERSAND, FLECHA, COMA, 
 PUNTO_COMA, MAS, MENOS, POR, DIV, MOD, EOF
}
