
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun May 08 19:48:22 CEST 2022
//----------------------------------------------------

package c_ast_ascendente;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int CORCHE_RECT_APER = 38;
  public static final int SEP_SECCION = 2;
  public static final int DISTINTO = 46;
  public static final int POR = 52;
  public static final int ARRAY = 30;
  public static final int LIT_CADENA = 59;
  public static final int WRITE = 36;
  public static final int DELETE = 34;
  public static final int CORCHE_CIER = 10;
  public static final int NOT = 18;
  public static final int AND = 16;
  public static final int IGUAL = 40;
  public static final int RECORD = 29;
  public static final int TYPE = 5;
  public static final int OR = 17;
  public static final int BOOL = 13;
  public static final int CALL = 28;
  public static final int PROCEDIMIENTO = 6;
  public static final int DIV = 53;
  public static final int PAR_CIER = 8;
  public static final int IF = 21;
  public static final int AMPERSAND = 47;
  public static final int IGUAL_IGUAL = 41;
  public static final int PUNTO_COMA = 3;
  public static final int ENDWHILE = 27;
  public static final int OF = 31;
  public static final int EOF = 0;
  public static final int TRUE = 14;
  public static final int NEW = 33;
  public static final int error = 1;
  public static final int COMA = 49;
  public static final int MENOS = 51;
  public static final int MENOR = 43;
  public static final int NULL = 20;
  public static final int MOD = 54;
  public static final int CORCHE_RECT_CIER = 39;
  public static final int MAYOR = 42;
  public static final int CORCHE_APER = 9;
  public static final int REAL = 12;
  public static final int ENT = 11;
  public static final int FLECHA = 48;
  public static final int ENDIF = 24;
  public static final int NUM_REAL = 58;
  public static final int ELSE = 23;
  public static final int PUNTO = 55;
  public static final int NL = 37;
  public static final int READ = 35;
  public static final int IDEN = 56;
  public static final int PAR_APER = 7;
  public static final int WHILE = 25;
  public static final int MAYOR_IGUAL = 44;
  public static final int THEN = 22;
  public static final int NUM_ENTERO = 57;
  public static final int STRING = 19;
  public static final int MENOR_IGUAL = 45;
  public static final int POINTER = 32;
  public static final int FALSE = 15;
  public static final int VAR = 4;
  public static final int DO = 26;
  public static final int MAS = 50;
}

