
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon Mar 21 14:28:26 CET 2022
//----------------------------------------------------

package asintCup;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int CORCHE_RECT_APER = 42;
  public static final int SEP_SECCION = 2;
  public static final int DISTINTO = 50;
  public static final int POR = 56;
  public static final int ARRAY = 31;
  public static final int LIT_CADENA = 39;
  public static final int WRITE = 37;
  public static final int DELETE = 35;
  public static final int CORCHE_CIER = 11;
  public static final int NOT = 19;
  public static final int AND = 17;
  public static final int IGUAL = 44;
  public static final int RECORD = 30;
  public static final int TYPE = 6;
  public static final int OR = 18;
  public static final int BOOL = 14;
  public static final int CALL = 29;
  public static final int PROCEDIMIENTO = 7;
  public static final int DIV = 57;
  public static final int PAR_CIER = 9;
  public static final int IF = 22;
  public static final int AMPERSAND = 51;
  public static final int IGUAL_IGUAL = 45;
  public static final int PUNTO_COMA = 3;
  public static final int ENDWHILE = 28;
  public static final int OF = 32;
  public static final int EOF = 0;
  public static final int TRUE = 15;
  public static final int NEW = 34;
  public static final int error = 1;
  public static final int COMA = 53;
  public static final int MENOS = 55;
  public static final int MENOR = 47;
  public static final int NULL = 21;
  public static final int MOD = 58;
  public static final int CORCHE_RECT_CIER = 43;
  public static final int MAYOR = 46;
  public static final int CORCHE_APER = 10;
  public static final int REAL = 13;
  public static final int ENT = 12;
  public static final int FLECHA = 52;
  public static final int ENDIF = 25;
  public static final int NUM_REAL = 41;
  public static final int ELSE = 24;
  public static final int PUNTO = 59;
  public static final int NL = 38;
  public static final int READ = 36;
  public static final int IDEN = 5;
  public static final int PAR_APER = 8;
  public static final int WHILE = 26;
  public static final int MAYOR_IGUAL = 48;
  public static final int THEN = 23;
  public static final int NUM_ENTERO = 40;
  public static final int STRING = 20;
  public static final int MENOR_IGUAL = 49;
  public static final int POINTER = 33;
  public static final int FALSE = 16;
  public static final int VAR = 4;
  public static final int DO = 27;
  public static final int MAS = 54;
}

