/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTinyConstants.java */
package asintCC;

public interface AnalizadorSintacticoTinyConstants {

  int EOF = 0;
  int letra = 1;
  int digitoPositivo = 2;
  int digito = 3;
  int parteEntera = 4;
  int parteDecimal = 5;
  int parteExponencial = 6;
  int ent = 9;
  int real = 10;
  int bool = 11;
  int True = 12;
  int False = 13;
  int and = 14;
  int or = 15;
  int not = 16;
  int string = 17;
  int Null = 18;
  int procedimiento = 19;
  int If = 20;
  int Then = 21;
  int Else = 22;
  int endif = 23;
  int While = 24;
  int Do = 25;
  int endwhile = 26;
  int call = 27;
  int record = 28;
  int array = 29;
  int of = 30;
  int pointer = 31;
  int New = 32;
  int delete = 33;
  int read = 34;
  int write = 35;
  int nl = 36;
  int var = 37;
  int type = 38;
  int lit_cadena = 39;
  int numeroEntero = 40;
  int numeroReal = 41;
  int iden = 42;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digitoPositivo>",
    "<digito>",
    "<parteEntera>",
    "<parteDecimal>",
    "<parteExponencial>",
    "<token of kind 7>",
    "<token of kind 8>",
    "\"int\"",
    "\"real\"",
    "\"bool\"",
    "\"true\"",
    "\"false\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"string\"",
    "\"null\"",
    "\"proc\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"endif\"",
    "\"while\"",
    "\"do\"",
    "\"endwhile\"",
    "\"call\"",
    "\"record\"",
    "\"array\"",
    "\"of\"",
    "\"pointer\"",
    "\"new\"",
    "\"delete\"",
    "\"read\"",
    "\"write\"",
    "\"nl\"",
    "\"var\"",
    "\"type\"",
    "<lit_cadena>",
    "<numeroEntero>",
    "<numeroReal>",
    "<iden>",
    "\"&\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"/\"",
    "\"%\"",
    "\".\"",
    "\"->\"",
  };

}
