package asint;

import asint.TinyASint.Suma;
import asint.TinyASint.TipoBool;
import asint.TinyASint.TipoEntero;
import asint.TinyASint.TipoReal;
import asint.TinyASint.TipoString;
import asint.TinyASint.TipoVar_iden;
import asint.TinyASint.TipoVar_pointer;
import asint.TinyASint.Resta;
import asint.TinyASint.Mul;
import asint.TinyASint.Negativo;
import asint.TinyASint.NotOperation;
import asint.TinyASint.Nulo;
import asint.TinyASint.OPDec;
import asint.TinyASint.Div;
import asint.TinyASint.Else_muchos;
import asint.TinyASint.Else_ninguno;
import asint.TinyASint.Entero;
import asint.TinyASint.FalseExp;
import asint.TinyASint.Flecha;
import asint.TinyASint.IdenExp;
import asint.TinyASint.Igual_igual;
import asint.TinyASint.Inst_asig;
import asint.TinyASint.Inst_bloque;
import asint.TinyASint.Inst_call;
import asint.TinyASint.Inst_delete;
import asint.TinyASint.Inst_if;
import asint.TinyASint.Inst_new;
import asint.TinyASint.Inst_nl;
import asint.TinyASint.Inst_read;
import asint.TinyASint.Inst_while;
import asint.TinyASint.Inst_write;
import asint.TinyASint.ListaCampos_muchos;
import asint.TinyASint.LitExp;
import asint.TinyASint.Mayor_igual_que;
import asint.TinyASint.Mayor_que;
import asint.TinyASint.Menor_igual_que;
import asint.TinyASint.Menor_que;
import asint.TinyASint.Mod;
import asint.TinyASint.OrOperation;
import asint.TinyASint.ParamReales_muchos;
import asint.TinyASint.ParamReales_ninguno;
import asint.TinyASint.ParamReales_uno;
import asint.TinyASint.Param_amps;
import asint.TinyASint.Param_normal;
import asint.TinyASint.PointerAst;
import asint.TinyASint.Prog_con_decs;
import asint.TinyASint.Prog_sin_decs;
import asint.TinyASint.AndOperation;
import asint.TinyASint.Array;
import asint.TinyASint.Bloque_con;
import asint.TinyASint.Bloque_sin;
import asint.TinyASint.Campo;
import asint.TinyASint.Dec_proc;
import asint.TinyASint.Distinto_distinto;
import asint.TinyASint.SDec_muchas ;
import asint.TinyASint.SDec_una;
import asint.TinyASint.SInst_muchas;
import asint.TinyASint.SInst_una;
import asint.TinyASint.Real;
import asint.TinyASint.TipoVar_array;
import asint.TinyASint.ListaCampos_uno;
import asint.TinyASint.Lista_param_muchos;
import asint.TinyASint.Lista_param_uno;
import asint.TinyASint.TipoVar_record;
import asint.TinyASint.TrueExp;
import asint.TinyASint.Punto;
import asint.TinyASint.Dec_type;
import asint.TinyASint.Dec_var;

//Donde puedo procesar los diferentes tipos de nodos
public interface Procesamiento {
    void procesa(Suma exp);
    void procesa(Resta exp);
    void procesa(AndOperation exp);
    void procesa(OrOperation exp);
    void procesa(Mayor_que exp);
    void procesa(Menor_que exp);
    void procesa(Mayor_igual_que exp);
    void procesa(Menor_igual_que exp);
    void procesa(Igual_igual exp);
    void procesa(Distinto_distinto exp);
    void procesa(Mul exp);
    void procesa(Div exp);
    void procesa(Negativo exp);
    void procesa(NotOperation exp);
    void procesa(Entero exp);
    void procesa(Real exp);
    void procesa(SDec_muchas decs);
    void procesa(SDec_una decs);
    void procesa(SInst_muchas sInst_muchas);
    void procesa(SInst_una sInst_una);
    void procesa(Prog_sin_decs prog_sin_decs);
    void procesa(Prog_con_decs prog_con_decs);
    void procesa(Punto punto);
    void procesa(Flecha flecha);
    void procesa(Array array);
    void procesa(PointerAst pointerAst);
    void procesa(IdenExp idenExp);
    void procesa(LitExp litExp);
    void procesa(Nulo nulo);
    void procesa(Mod mod);
    void procesa(TipoVar_iden tipoVar_iden);
    void procesa(TipoVar_pointer tipoVar_pointer);
    void procesa(Else_muchos else_muchos);
    void procesa(ParamReales_muchos paramReales_muchos);
    void procesa(ParamReales_uno paramReales_uno);
    void procesa(TipoVar_record tipoVar_record);
    void procesa(TipoVar_array tipoVar_array);
    void procesa(ListaCampos_muchos listaCampos_muchos);
    void procesa(ListaCampos_uno listaCampos_uno);
    void procesa(Campo campo);
    void procesa(Dec_proc dec_proc);
    void procesa(Dec_type dec_type);
    void procesa(Dec_var dec_var);
    void procesa(Lista_param_muchos lista_param_muchos);
    void procesa(Lista_param_uno lista_param_uno);
    void procesa(Param_amps param_amps);
    void procesa(Param_normal param_normal);
    void procesa(OPDec opDec);
    void procesa(TipoEntero tipoEntero);
    void procesa(TipoReal tipoReal);
    void procesa(TipoBool tipoBool);
    void procesa(TipoString tipoString);
    void procesa(TrueExp trueExp);
    void procesa(FalseExp falseExp);
    void procesa(ParamReales_ninguno paramReales_ninguno);
    void procesa(Else_ninguno else_ninguno);
    void procesa(Bloque_con bloque_con);
    void procesa(Bloque_sin bloque_sin);
    void procesa(Inst_asig inst_asig);
    void procesa(Inst_if inst_if);
    void procesa(Inst_while inst_while);
    void procesa(Inst_read inst_read);
    void procesa(Inst_write inst_write);
    void procesa(Inst_nl inst_nl);
    void procesa(Inst_new inst_new);
    void procesa(Inst_delete inst_delete);
    void procesa(Inst_call inst_call);
    void procesa(Inst_bloque inst_bloque);
}